<Project>
  <PropertyGroup>
    <AndroidSdkDirectory Condition="'$(AndroidSdkDirectory)' == '' and Exists('$(LOCALAPPDATA)\Android\Sdk')">$(LOCALAPPDATA)\Android\Sdk</AndroidSdkDirectory>
    <JavaSdkDirectory Condition="'$(JavaSdkDirectory)' == '' and Exists('$(LOCALAPPDATA)\Android\Jdk')">$(LOCALAPPDATA)\Android\Jdk</JavaSdkDirectory>
  </PropertyGroup>
</Project>
